# Word2Vec Topic - K-Means Modeling Tutorial

In [1]:
# Required to display widgets in Jupyter
import os
import sys

#This will navigate up two levels in the directory structure to the project root directory. 
sys.path.append(os.path.dirname(os.getcwd()))

# # Import to minimize warning. 
import warnings

#warnings.filterwarnings('ignore', category=DeprecationWarning)
with warnings.catch_warnings():
    warnings.simplefilter("ignore")

from topicminer import Word2Vec_KMeans_Cat, read_json_to_dataframe

# Summary

# Train the Model

The Word2VecKMeansCategorizer class in Python is designed to cluster documents using Word2Vec embeddings followed by KMeans clustering. When an instance of this class is created, it's configured with specific parameters such as the size of the embeddings, window size for context words, minimum count of word occurrences, number of training epochs, and the number of clusters. The class provides methods to train a Word2Vec model on the provided documents, which converts words into numerical vector representations. It then uses these vectors to compute document-level embeddings by averaging the embeddings of words within each document. These document vectors are then clustered using the KMeans algorithm. Additionally, the class can extract and display the most representative terms for each cluster, facilitating an understanding of the dominant themes or topics within the clusters. This class streamlines the process of transforming unstructured text data into a structured format that can be easily analyzed or used for further machine learning tasks.

In [2]:
categorizer = Word2Vec_KMeans_Cat(n_clusters=10, num_unique_terms=10)

# Topics

In [3]:
categorizer.show_topics()

           Word[0]       Word[1]       Word[2]   Word[3]       Word[4]      Word[5]    Word[6]      Word[7]      Word[8]     Word[9]
Labels
0             ever      internal      electric     found        social     thinking       lost       policy           or       larry
1            trust         hello        market     tough  optimization  competitive  proactive  willingness     electric      report
2           market         hello         water      only          grab     electric     saying       either     industry       drama
3            trust          ever   competitive  backbone     milestone     electric     social    landscape        crush       every
4       developing      internal  implementing  consider           ibm     electric  milestone        ahead        steps  dedication
5             tech  implementing      electric     donna          root      assured     tasked     industry      abreast   landscape
6       constantly     proactive      spinning  electric         donna        ahead   industry      involve     thinking        lost
7        brilliant     listening     quicksand  electric          rest        major   thinking        every       losing       larry
8         upcoming      electric        social        in         larry       better       work  opportunity         love        find
9            smile    everything          grab  entirely      electric        ahead     policy        every  engineering        suck

In [4]:
full_df = tokenized_docs = read_json_to_dataframe()
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3165 entries, 0 to 3164
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   doc_id             3165 non-null   object
 1   date               3165 non-null   object
 2   email_recipient    3165 non-null   object
 3   email_sender       3165 non-null   object
 4   email_cc           3165 non-null   object
 5   email_bcc          3165 non-null   object
 6   email_subject      3165 non-null   object
 7   email_attachments  3165 non-null   object
 8   email_categories   3165 non-null   object
 9   email_body         3165 non-null   object
 10  processed_text     3165 non-null   object
 11  word_count         3165 non-null   int64
 12  character_count    3165 non-null   int64
 13  token_count        3165 non-null   int64
 14  file_path          3165 non-null   object
 15  lda_topics         3165 non-null   object
dtypes: int64(3), object(13)
memory usage: 395.8+ KB

In [6]:
emails_df, key_terms = categorizer.categorize_documents()
#full_df = tokenized_docs = read_json_to_dataframe()['doc_id']

In [7]:
emails_df['Cluster']

0       5
1       8
2       6
3       3
4       8
       ..
3160    8
3161    6
3162    9
3163    8
3164    1
Name: Cluster, Length: 3165, dtype: int32

In [48]:
import pandas as pd

# Imoprt the emails_df and key terms. 
emails_df = read_json_to_dataframe()
tokens_df, key_terms = categorizer.categorize_documents()
key_terms = pd.DataFrame(key_terms).T

# Combine the key terms into rows of lists and feed them back into the dataframe.
dict = {}
for i,row in key_terms.iterrows():
    row_ = row.to_list()
    row_str = ', '.join(row_)
    row_ = [row_str]
    dict[i] = row_
print(dict)

key_terms = pd.DataFrame(dict).T
emails_df = pd.merge(emails_df, key_terms, left_index=True, right_index=True, how='left')

{0: ['ever, internal, electric, found, social, thinking, lost, policy, or, larry'], 1: ['trust, hello, market, tough, optimization, competitive, proactive, willingness, electric, report'], 2: ['market, hello, water, only, grab, electric, saying, either, industry, drama'], 3: ['trust, ever, competitive, backbone, milestone, electric, social, landscape, crush, every'], 4: ['developing, internal, implementing, consider, ibm, electric, milestone, ahead, steps, dedication'], 5: ['tech, implementing, electric, donna, root, assured, tasked, industry, abreast, landscape'], 6: ['constantly, proactive, spinning, electric, donna, ahead, industry, involve, thinking, lost'], 7: ['brilliant, listening, quicksand, electric, rest, major, thinking, every, losing, larry'], 8: ['upcoming, electric, social, in, larry, better, work, opportunity, love, find'], 9: ['smile, everything, grab, entirely, electric, ahead, policy, every, engineering, suck']}

In [51]:
 emails_df.head(2)

,doc_id,date,email_recipient,email_sender,email_cc,email_bcc,email_subject,email_attachments,email_categories,email_body,processed_text,word_count,character_count,token_count,file_path,lda_topics,0
0,e9339f78b82b763605774d9376f2e7e78a58ec895dca66071853367ccd7f2d5c,"Wednesday, February 23, 1983 02:59 PM",Debbie Malinowski; Joe MacMillan; John Bosworth; Donna Clark; Gordon Clark; Yo-Yo Engberk; Malcolm Levitan; Larry Goins; Barry Shields; Cameron Howe,Ed Burris,No CC,No BCC,Internal Announcement - Project Prioritization and Alignment,No Attachments,Internal Announcement,"Dear Team,\nAs we continue to drive innovation and growth at Cardiff Electric, I wanted to take a moment to discuss project prioritization and alignment. With our current pipeline of initiatives, it's essential that we focus on the most critical projects that align with our strategic objectives.\nTo ensure we're working efficiently and effectively, please find below key takeaways and action items:\n• Review project charts and provide input by EOD Friday\n• Identify top three priorities for each project by COB Monday\n• Attend project alignment meeting on Tuesday at 2 PM to discuss and refine priorities\nI understand this may require some extra effort from each of you, but I'm confident that our collective expertise will yield positive results.\nPlease let me know if you have any questions or concerns. I look forward to reviewing your input and discussing the next steps on Tuesday.\nBest regards,\nEd Burris\nProject Manager, Cardiff Electric\nPhone: +1 512-555-0155",internal announcement project prioritization alignment dear team continue drive innovation growth cardiff electric wanted take moment discus project prioritization alignment with current pipeline initiative essential focus critical project align strategic objective ensure working efficiently effectively please find key takeaway action item review project chart provide input eod friday identify top three priority project cob monday attend project alignment meeting tuesday discus refine priority understand may require extra effort confident collective expertise yield positive result please let know question concern look forward reviewing input discussing next step tuesday best regard burris project manager cardiff electric phone,157,967,95,/home/aaronnhorvitz/dev/work/irs/TopicMiner/data/raw_data/01361.txt,"{'2': 0.9582228660583496, '3': 0.0350380539894104}","ever, internal, electric, found, social, thinking, lost, policy, or, larry"
1,cef9039181698cc0d3ca257a2a6512ea2190cf750b6357c62177f44c8ef1ce3c,"Tuesday, February 01, 1983 04:19 PM",Joe MacMillan,Barry Shields,No CC,No BCC,Social Event Invitation,No Attachments,Social Event,"Dear Joe,\nI am writing to extend an invitation to you to attend a social event hosted by Cardiff Electric's Legal department. As part of our team-building efforts, we have organized a networking evening and I would be delighted if you could join us.\nThe event will take place on Friday, March 18th at 6:00 PM at the Hyatt Regency Downtown. This will provide an opportunity for colleagues to mingle in a relaxed atmosphere, fostering greater collaboration and camaraderie within our team.\nI do hope you can attend. Your presence would be greatly valued.\nSincerely,\nBarry Shields\nSenior Counsel\nCardiff Electric - Legal\n+1 512-555-0166",social event invitation dear joe writing extend invitation attend social event hosted cardiff electric legal department part effort organized networking evening would delighted could join the event take place friday march hyatt regency downtown this provide opportunity colleague mingle relaxed atmosphere fostering greater collaboration camaraderie within team hope attend your presence would greatly valued sincerely barry shields senior counsel cardiff electric legal,105,633,62,/home/aaronnhorvitz/dev/work/irs/TopicMiner/data/raw_data/00679.txt,"{'2': 0.8817122578620911, '3': 0.10748717933893204}","trust, hello, market, tough, optimization, competitive, proactive, willingness, electric, report"

In [44]:
emails_df

In [41]:
emails_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3165 entries, 0 to 3164
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Email    3165 non-null   object
 1   Cluster  3165 non-null   int32
dtypes: int32(1), object(1)
memory usage: 37.2+ KB

In [9]:
import pandas as pd

In [17]:

pd.DataFrame(key_terms).T

            0             1             2         3             4            5          6            7            8           9
0        ever      internal      electric     found        social     thinking       lost       policy           or       larry
1       trust         hello        market     tough  optimization  competitive  proactive  willingness     electric      report
2      market         hello         water      only          grab     electric     saying       either     industry       drama
3       trust          ever   competitive  backbone     milestone     electric     social    landscape        crush       every
4  developing      internal  implementing  consider           ibm     electric  milestone        ahead        steps  dedication
5        tech  implementing      electric     donna          root      assured     tasked     industry      abreast   landscape
6  constantly     proactive      spinning  electric         donna        ahead   industry      involve     thinking        lost
7   brilliant     listening     quicksand  electric          rest        major   thinking        every       losing       larry
8    upcoming      electric        social        in         larry       better       work  opportunity         love        find
9       smile    everything          grab  entirely      electric        ahead     policy        every  engineering        suck

In [13]:
key_terms

{0: ['ever',
  'internal',
  'electric',
  'found',
  'social',
  'thinking',
  'lost',
  'policy',
  'or',
  'larry'],
 1: ['trust',
  'hello',
  'market',
  'tough',
  'optimization',
  'competitive',
  'proactive',
  'willingness',
  'electric',
  'report'],
 2: ['market',
  'hello',
  'water',
  'only',
  'grab',
  'electric',
  'saying',
  'either',
  'industry',
  'drama'],
 3: ['trust',
  'ever',
  'competitive',
  'backbone',
  'milestone',
  'electric',
  'social',
  'landscape',
  'crush',
  'every'],
 4: ['developing',
  'internal',
  'implementing',
  'consider',
  'ibm',
  'electric',
  'milestone',
  'ahead',
  'steps',
  'dedication'],
 5: ['tech',
  'implementing',
  'electric',
  'donna',
  'root',
  'assured',
  'tasked',
  'industry',
  'abreast',
  'landscape'],
 6: ['constantly',
  'proactive',
  'spinning',
  'electric',
  'donna',
  'ahead',
  'industry',
  'involve',
  'thinking',
  'lost'],
 7: ['brilliant',
  'listening',
  'quicksand',
  'electric',
  'rest',
  'major',
  'thinking',
  'every',
  'losing',
  'larry'],
 8: ['upcoming',
  'electric',
  'social',
  'in',
  'larry',
  'better',
  'work',
  'opportunity',
  'love',
  'find'],
 9: ['smile',
  'everything',
  'grab',
  'entirely',
  'electric',
  'ahead',
  'policy',
  'every',
  'engineering',
  'suck']}

In [12]:
len(label_key_terms_dicct)

10